### ISSUE TITLE
Can't get explorer working with private geth blockchain (POA)

### ISSUE THREAD

**Issue by alexacostarua** [ethereumproject/explorer#160]
This is the error I get.

EthereumClassicExplorer@0.2.0 start /home/user1/explorer-master
> concurrently "node tools/sync.js " "node app.js" 

[0] config.json found.
[0] Connecting localhost:8545...
[0] Checking for missing blocks
[1] module.js:549
[1]     throw err;
[1]     ^
[1] 

Im using npm version 5.6.
[1] Error: Cannot find module 'async'
[1]     at Function.Module._resolveFilename (module.js:547:15)
[1]     at Function.Module._load (module.js:474:25)
[1]     at Module.require (module.js:596:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (/home/user1/explorer-master/routes/index.js:7:13)
[1]     at Module._compile (module.js:652:30)
[1]     at Object.Module._extensions..js (module.js:663:10)
[1]     at Module.load (module.js:565:32)
[1]     at tryModuleLoad (module.js:505:12)
[1]     at Function.Module._load (module.js:497:3)
[1]     at Module.require (module.js:596:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (/home/user1/explorer-master/app.js:51:1)
[1]     at Module._compile (module.js:652:30)
[1]     at Object.Module._extensions..js (module.js:663:10)
[1]     at Module.load (module.js:565:32)
[1] node app.js exited with code 1
[0] Starting Full Sync
[0] (node:9633) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/4.x/docs/connections.html#use-mongo-client
[0] (node:9633) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
[0] 
[0] events.js:183
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0] MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
[0]     at Pool.<anonymous> (/home/user1/explorer-master/node_modules/mongodb-core/lib/topologies/server.js:336:35)
[0]     at emitOne (events.js:116:13)
[0]     at Pool.emit (events.js:211:7)
[0]     at Connection.<anonymous> (/home/user1/explorer-master/node_modules/mongodb-core/lib/connection/pool.js:280:12)
[0]     at Object.onceWrapper (events.js:317:30)
[0]     at emitTwo (events.js:126:13)
[0]     at Connection.emit (events.js:214:7)
[0]     at Socket.<anonymous> (/home/user1/explorer-master/node_modules/mongodb-core/lib/connection/connection.js:189:49)
[0]     at Object.onceWrapper (events.js:315:30)
[0]     at emitOne (events.js:116:13)
[0]     at Socket.emit (events.js:211:7)
[0]     at emitErrorNT (internal/streams/destroy.js:64:8)
[0]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[0]     at process._tickCallback (internal/process/next_tick.js:180:9)
[0] node tools/sync.js  exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! EthereumClassicExplorer@0.2.0 start: `concurrently "node tools/sync.js " "node app.js" `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the EthereumClassicExplorer@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by mikeyb** [comment]
`[0] MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]`

**Comment by alexacostarua** [comment]
Ok.  I see the error.  How would I fix this.  Would I use : 
var promise = mongoose.connect('mongodb://localhost/myapp', {
  useMongoClient: true,
  /* other options */
});
// Or `createConnection`
var promise = mongoose.createConnection('mongodb://localhost/myapp', {
  useMongoClient: true,
  /* other options */
});
promise.then(function(db) {
  /* Use `db`, for instance `db.model()`
});
// Or, if you already have a connection
connection.openUri('mongodb://localhost/myapp', { /* options */ });
----------------------------------------------------------------------------------------------------------------------------------
Or how exactly would you recommend I fix this?
@mikeyb

**Comment by mikeyb** [comment]
Run through the install instructions again.  You dont have mongo running so when it tries to connect it fails since mongo isnt running.  Make sure there are no errors when running `npm install` and make sure you are not using ubuntus built in npm.

If you still have issues, we need more details of your setup.  I am basically guessing in the dark

**Comment by alexacostarua** [comment]
Ok.  npm install worked perfect with only a few warnings, but when I ran  sudo apt-get install -y mongodb-org
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?

Not sure what other process would be using it, I just started up this machine as well.

**Comment by alexacostarua** [comment]
Alright I ran those commands then retryed the command but was returned with : sudo apt-get install -y mongodb-org
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package mongodb-org

**Comment by mikeyb** [comment]
`ps aux|grep apt` should tell you what process is running apt.  If you rebooted the system with apt running (ie, no apt processes running currently), try removing the lock file and trying again.

**Comment by mikeyb** [comment]
try just `apt-get install mongodb` mongodb-org doesnt exist on ubuntu.  directions on readme might be out of date

**Comment by alexacostarua** [comment]
Ok.  Ive installed the mongodb following the https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/ 
> EthereumClassicExplorer@0.2.0 start /home/user1/ethprojexplorer
> concurrently "node tools/sync.js " "node app.js" 

[0] config.json found.
[0] Connecting localhost:8545...
[0] Checking for missing blocks
[1] CONFIG FOUND: Node:localhost | Port:8545
[0] Starting Full Sync
[1] Web3 connection established
[0] (node:7870) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/4.x/docs/connections.html#use-mongo-client
[0] (node:7870) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
[0] 
[0] events.js:183
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0] MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
[0]     at Pool.<anonymous> (/home/user1/ethprojexplorer/node_modules/mongodb-core/lib/topologies/server.js:336:35)
[0]     at emitOne (events.js:116:13)
[0]     at Pool.emit (events.js:211:7)
[0]     at Connection.<anonymous> (/home/user1/ethprojexplorer/node_modules/mongodb-core/lib/connection/pool.js:280:12)
[0]     at Object.onceWrapper (events.js:317:30)
[0]     at emitTwo (events.js:126:13)
[0]     at Connection.emit (events.js:214:7)
[0]     at Socket.<anonymous> (/home/user1/ethprojexplorer/node_modules/mongodb-core/lib/connection/connection.js:189:49)
[0]     at Object.onceWrapper (events.js:315:30)
[0]     at emitOne (events.js:116:13)
[0]     at Socket.emit (events.js:211:7)
[0]     at emitErrorNT (internal/streams/destroy.js:64:8)
[0]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[0]     at process._tickCallback (internal/process/next_tick.js:180:9)
[0] node tools/sync.js  exited with code 1
[1] (node:7876) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/4.x/docs/connections.html#use-mongo-client
[1] Express server listening on port 3000
[1] 
[1] /home/user1/ethprojexplorer/node_modules/solc/soljson.js:1
[1] (function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename);if(
[1] MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
[1]     at Pool.<anonymous> (/home/user1/ethprojexplorer/node_modules/mongodb-core/lib/topologies/server.js:336:35)
[1]     at emitOne (events.js:116:13)
[1]     at Pool.emit (events.js:211:7)
[1]     at Connection.<anonymous> (/home/user1/ethprojexplorer/node_modules/mongodb-core/lib/connection/pool.js:280:12)
[1]     at Object.onceWrapper (events.js:317:30)
[1]     at emitTwo (events.js:126:13)
[1]     at Connection.emit (events.js:214:7)
[1]     at Socket.<anonymous> (/home/user1/ethprojexplorer/node_modules/mongodb-core/lib/connection/connection.js:189:49)
[1]     at Object.onceWrapper (events.js:315:30)
[1]     at emitOne (events.js:116:13)
[1]     at Socket.emit (events.js:211:7)
[1]     at emitErrorNT (internal/streams/destroy.js:64:8)
[1]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[1]     at process._tickCallback (internal/process/next_tick.js:180:9)
[1] node app.js exited with code 7
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! EthereumClassicExplorer@0.2.0 start: `concurrently "node tools/sync.js " "node app.js" `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the EthereumClassicExplorer@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.6.0 → 6.3.0    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯


npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user1/.npm/_logs/2018-08-08T15_11_44_729Z-debug.log

**Comment by alexacostarua** [comment]
I installed it with "apt-get install mongodb" and it works.  Cheers! @mikeyb
