### ISSUE TITLE
Adding my custom token from my private network (Geth)

### ISSUE THREAD

**Issue by alexacostarua** [ethereumproject/explorer#161]
Ok so I've added my custom token.  To the public > tokens.json : I replaced the first one bitether with my credentials for the token.      replaced the contract address with my own "address":"0x7a44861Dc68e011004418c313879387fAefDE36e",
    "symbol":"CHY",
    "name": "ChewyToken",
    "decimal":18,
    "abi": [ (added my full abi code from Remix IDE)

I've successfully got 60000 of these CHY tokens sent to my ether address (says so in metamask), yet when I check the balance it says its zero.  The way my coin works if you send ether to its contract address it gives you 1000 coins to that same wallet.  No transactions show under the coin either. What else to I have to edit to get this to work.

**Comment by mikeyb** [comment]
OS, software versions, errors, do you see the CHY token listed under tokens in your explorer app, did you restart your explorer after making changes?  Things we need to know, all I know is your token name and address at this point.

**Comment by alexacostarua** [comment]
Ubuntu 16.04_LTS, geth1.8.13-stable-225171a4, it shows up when you hit view all tokens as the first option.  But from the token drop down menu it still shows bitether.  Do I need to verify my Contract Source Code under that tab at the bottom as well or something else going on?

----------------------------------------------------------------------------------------------------------------------------------
[1] GET /views/contract-source.html 304 0.401 ms - -
[1] { action: 'info' }
[1] Error: invalid address
[1]     at inputAddressFormatter (/home/user1/ethprojexplorer/node_modules/web3/lib/web3/formatters.js:271:11)
[1]     at /home/user1/ethprojexplorer/node_modules/web3/lib/web3/method.js:89:28
[1]     at Array.map (<anonymous>)
[1]     at Method.formatInput (/home/user1/ethprojexplorer/node_modules/web3/lib/web3/method.js:88:32)
[1]     at Method.toPayload (/home/user1/ethprojexplorer/node_modules/web3/lib/web3/method.js:114:23)
[1]     at Eth.send [as getBalance] (/home/user1/ethprojexplorer/node_modules/web3/lib/web3/method.js:139:30)
[1]     at module.exports (/home/user1/ethprojexplorer/routes/token.js:28:31)
[1]     at Layer.handle [as handle_request] (/home/user1/ethprojexplorer/node_modules/express/lib/router/layer.js:95:5)
[1]     at next (/home/user1/ethprojexplorer/node_modules/express/lib/router/route.js:137:13)
[1]     at Route.dispatch (/home/user1/ethprojexplorer/node_modules/express/lib/router/route.js:112:3)
[1]     at Layer.handle [as handle_request] (/home/user1/ethprojexplorer/node_modules/express/lib/router/layer.js:95:5)
[1]     at /home/user1/ethprojexplorer/node_modules/express/lib/router/index.js:281:22
[1]     at Function.process_params (/home/user1/ethprojexplorer/node_modules/express/lib/router/index.js:335:12)
[1]     at next (/home/user1/ethprojexplorer/node_modules/express/lib/router/index.js:275:10)
[1]     at serveStatic (/home/user1/ethprojexplorer/node_modules/serve-static/index.js:75:16)
[1]     at Layer.handle [as handle_request] (/home/user1/ethprojexplorer/node_modules/express/lib/router/layer.js:95:5)
[1] { action: 'find' }
[1] (node:5280) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
[1] POST /compile 200 10.623 ms - -
[1] GET /js/controllers/TokenListController.js 304 0.738 ms - -
[1] GET /views/tokenlist.html 304 0.797 ms - -
[1] GET /tokens.json 304 0.426 ms - -
[1] { action: 'info' }
[1] Error: invalid address
[1]     at inputAddressFormatter (/home/user1/ethprojexplorer/node_modules/web3/lib/web3/formatters.js:271:11)
[1]     at /home/user1/ethprojexplorer/node_modules/web3/lib/web3/method.js:89:28
[1]     at Array.map (<anonymous>)
[1]     at Method.formatInput (/home/user1/ethprojexplorer/node_modules/web3/lib/web3/method.js:88:32)
[1]     at Method.toPayload (/home/user1/ethprojexplorer/node_modules/web3/lib/web3/method.js:114:23)
[1]     at Eth.send [as getBalance] (/home/user1/ethprojexplorer/node_modules/web3/lib/web3/method.js:139:30)
[1]     at module.exports (/home/user1/ethprojexplorer/routes/token.js:28:31)
[1]     at Layer.handle [as handle_request] (/home/user1/ethprojexplorer/node_modules/express/lib/router/layer.js:95:5)
[1]     at next (/home/user1/ethprojexplorer/node_modules/express/lib/router/route.js:137:13)
[1]     at Route.dispatch (/home/user1/ethprojexplorer/node_modules/express/lib/router/route.js:112:3)
[1]     at Layer.handle [as handle_request] (/home/user1/ethprojexplorer/node_modules/express/lib/router/layer.js:95:5)
[1]     at /home/user1/ethprojexplorer/node_modules/express/lib/router/index.js:281:22
[1]     at Function.process_params (/home/user1/ethprojexplorer/node_modules/express/lib/router/index.js:335:12)
[1]     at next (/home/user1/ethprojexplorer/node_modules/express/lib/router/index.js:275:10)
[1]     at serveStatic (/home/user1/ethprojexplorer/node_modules/serve-static/index.js:75:16)
[1]     at Layer.handle [as handle_request] (/home/user1/ethprojexplorer/node_modules/express/lib/router/layer.js:95:5)
[1] { action: 'find' }
[1] POST /compile 200 2.314 ms - -

**Comment by mikeyb** [comment]
Sounds like you didnt update the dropdown menu

**Comment by hackmod** [comment]
> "address":"0x7a44861Dc68e011004418c313879387fAefDE36e"

you have to use all caps or all small for valid address.

or you can try to fix `public/js/web3utils.js`
~~~diff
diff --git a/public/js/web3utils.js b/public/js/web3utils.js
index 586e998..ce9b6e9 100644
--- a/public/js/web3utils.js
+++ b/public/js/web3utils.js
@@ -18,11 +18,8 @@ var isStrictAddress = function (address) {
  * @return {Boolean}
 */
 var isAddress = function (address) {
-    if (!/^(0x)?[0-9a-f]{40}$/i.test(address)) {
+    if (/^(0x)?[0-9a-fA-F]{40}$/i.test(address)) {
         // check if it has the basic requirements of an address
-        return false;
-    } else if (/^(0x)?[0-9a-f]{40}$/.test(address) || /^(0x)?[0-9A-F]{40}$/.test(address)) {
-        // If it's all small caps or all all caps, return true
         return true;
     } else {
         // Otherwise check each case
~~~

**Comment by mikeyb** [comment]
Checksum only works with the CORRECT uppercase letters fyi.
Checksum address are NOT ALL CAPS.

Is there a reason we require all upper or all lowercase for this check?  Mixed case is most certainly valid and the correct way to display a checksum'd address

https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md

**Comment by alexacostarua** [comment]
Word.  So it was correct the first time?  I have no clue whats wrong then.  Should I try editing theDao instead of the bitether one?

**Comment by hackmod** [comment]
@mikeyb // yes. checksumed address is correct and this is an old bug. (1ae067ae4fa117533)

**Comment by hackmod** [comment]
for example, MyEtherWallet use `ethereumjs-util`

~~~js
// etherwallet/app/scripts/ethFuncs.js
ethFuncs.validateEtherAddress = function(address) {
    if (address.substring(0, 2) != "0x") return false;
    else if (!/^(0x)?[0-9a-f]{40}$/i.test(address)) return false;
    else if (/^(0x)?[0-9a-f]{40}$/.test(address) || /^(0x)?[0-9A-F]{40}$/.test(address)) return true;
    else
        return this.isChecksumAddress(address);
}
ethFuncs.isChecksumAddress = function(address) {
    return address == ethUtil.toChecksumAddress(address);
}
...
~~~
